# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора



```
# This is formatted as code
```

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

arr = np.random.uniform(0, 20, size=(4, 7))

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())

print("Исходный массив:")
print(arr)
print("\nНормализованный массив:")
print(normalized_arr)

Исходный массив:
[[14.51056368 10.14452356 12.02037572 13.18793643 16.13867176  9.92409186
   5.19014866]
 [ 2.67122851  3.76769781 18.20324947  7.24874636  5.88615866  5.62134202
   4.36537982]
 [ 1.63269243 16.8735935   3.19537357  1.87705    15.66090067 12.55757316
   8.23976658]
 [ 4.72939657 17.18241139 18.70572024 14.05512229 19.89218836 17.0924095
   8.47007338]]

Нормализованный массив:
[[0.70526981 0.46615915 0.56889212 0.63283478 0.79443482 0.45408698
  0.19482774]
 [0.05687649 0.11692576 0.90750353 0.30756895 0.23294544 0.21844248
  0.14965842]
 [0.         0.83468356 0.08558183 0.01338249 0.7682692  0.59831228
  0.36184318]
 [0.16959417 0.85159629 0.93502186 0.6803271  1.         0.84666724
  0.37445617]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
new_matrix = np.random.randint(0, 11, size=(8, 10))
print(new_matrix)

smallest_sum = min(i for i in [sum(j) for j in new_matrix])

result_string = [j for j in new_matrix if sum(j) == smallest_sum][0]

a = [sum(i) for i in new_matrix]
for i in range(len(a)):
  if a[i] == sum(result_string):
    index = i + 1
    break

print(result_string, index)


[[ 2  2 10  6  3 10  5 10  5  3]
 [10  1  8  2  8  1  4  1  8  1]
 [ 3  7  5  9  9  3  9 10  8  7]
 [ 9  9  4  5 10  2  4  6  5  8]
 [10  1  7  7  7  4 10  2  6  5]
 [ 4  4  5  3  0  7  6  7  8  6]
 [ 9  9  4  6  8  7  3  2  4  0]
 [ 4  5  7  0  3  3 10  0  2  7]]
[ 4  5  7  0  3  3 10  0  2  7] 8


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import math
arr1 = np.arange(3).reshape(3, 1)
arr2 = np.arange(10, 13).reshape(3, 1)
distance = math.dist(arr1, arr2)  # возвращает евклидово расстояние между двумя векторами
print(distance)

17.320508075688775


<ipython-input-9-b3d9e2b4afd1>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  distance = math.dist(arr1, arr2)  # возвращает евклидово расстояние между двумя векторами


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
negative_C = np.array([[7, 21], [11, 8], [8, 4]]) * (-1)

# Решить матричное уравнение A*X*B=-C
# X = A^(-1) * (-C) * B^(-1)

A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)
X = np.dot(A_inverse, negative_C)
X = np.dot(X, B_inverse)

print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('minutes_n_ingredients.csv', skiprows=1, header=None)

numpy_array = np.array(data)

print(numpy_array[:5])

print(np.sum(numpy_array[:, 1] == 0))

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]
479


In [ ]:
import numpy as np
a = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
print(a[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
import numpy as np
import pandas as pd
import statistics

data = pd.read_csv('minutes_n_ingredients.csv', skiprows=1, header=None)

numpy_array = np.array(data)

# Среднее значение по 1 столбцу:
print((numpy_array[:, 1]).sum(axis=0) / 100000)

# Среднее значение по 2 столбцу:
print((numpy_array[:, 2]).sum(axis=0) / 100000)

# Минимальное по 1 столбцу
print(min(numpy_array[:, 1]))

# Минимальное по 2 столбцу
print(min(numpy_array[:, 2]))

# Максимальное по 1 столбцу
print(max(numpy_array[:, 1]))

# Максимальное по 2 столбцу
print(max(numpy_array[:, 2]))

# Медиана по 1 столбцу
print(statistics.median(numpy_array[:, 1]))

# Медиана по 2 столбцу
print(statistics.median(numpy_array[:, 2]))

21601.00169
9.05528
0
1
2147483647
39
40.0
9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
import numpy as np
a = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
print(np.quantile(a[:, 1], .75))

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(np.sum(numpy_array[:, 1] == 0))
#(numpy_array[:, 1])[numpy_array[:, 1] == 0] = 1

print(np.sum(numpy_array[:, 1] == 0))

479
479



5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(numpy_array[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(numpy_array[:, 2]))
print(len(np.unique(numpy_array[:, 2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
some_reciped = (numpy_array)[numpy_array[:, 2] <= 5]
print(some_reciped)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
average_ingredients = numpy_array[:, 2] / numpy_array[:, 1]
print(average_ingredients)
print(max(average_ingredients))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
inf


<ipython-input-19-6c1ac1e83294>:1: RuntimeWarning: divide by zero encountered in divide
  average_ingredients = numpy_array[:, 2] / numpy_array[:, 1]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
import statistics
top_100_recipes = numpy_array[numpy_array[:, 1].argsort()][::-1][:100]
print(top_100_recipes)
average_ingredients = top_100_recipes[:, 2].sum(axis=0) / 100
print(average_ingredients)

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
random_recipes = np.random.randint(numpy_array.shape[0], size=10)
print(random_recipes)
numpy_array[random_recipes, :], random_recipes

[61900 13811 78057 77206 72029 43829 86200 24624 17791 90905]


(array([[ 84517,    130,      9],
        [486019,     30,     12],
        [182464,     15,     11],
        [279732,     10,      5],
        [305016,     30,      9],
        [361957,     20,     10],
        [334803,     35,     12],
        [243626,     80,      9],
        [  4019,      0,     15],
        [  4807,      0,      3]]),
 array([61900, 13811, 78057, 77206, 72029, 43829, 86200, 24624, 17791,
        90905]))

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
less_average = numpy_array[numpy_array[:, 2] < ((numpy_array[:, 2]).sum(axis=0) / 100000)]
p = len(less_average) / len(numpy_array)
print(p * 100, "%")

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
easy_recipes = np.zeros((numpy_array.shape[0], 4), dtype=int)
easy_recipes[:, :3] = numpy_array
easy_recipes[np.where((numpy_array[:, 2] <= 5) & (numpy_array[:, 1] <= 20)), 3] = 1
print(easy_recipes)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
str(sum(easy_recipes[:, 3]) / easy_recipes.shape[0] * 100) + "%"

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.